import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform
import com.pswidersk.gradle.python.uv.*

plugins {
    id "com.github.node-gradle.node" version "7.1.0"
    id "com.pswidersk.python-uv-plugin" version "0.4.29"
}

node {
    version = '26.0.0'
    yarnVersion = '1.5.1'
    download = true
}

repositories {
    mavenCentral()
    maven {
        url = 'https://gradle.org'
    }
}

def emscriptenLocation = "$rootDir/.emscripten"
def emscriptenVersion = "6.0.11"
String emsdkCmd = "$emscriptenLocation/emsdk-$emscriptenVersion/emsdk"
String emsdkEnvCmd = "$emscriptenLocation/emsdk-$emscriptenVersion/emsdk_env"
OperatingSystem os = DefaultNativePlatform.currentOperatingSystem

String emccCmd = "$emscriptenLocation/emsdk-$emscriptenVersion/upstream/emscripten/emcc"
if (os.toFamilyName() == 'windows') {
    emsdkCmd += ".bat"
    emccCmd += ".exe"
    emsdkEnvCmd += ".bat"
}

File outputDirectory = new File(rootDir, '/client/public/assets/wasm') //layout.buildDirectory.dir('wasm').get().asFile
String outputJsPath = new File(outputDirectory, 'engine-module.js').absolutePath

// 1. The Diagnostic Version Check Task
tasks.register('checkEmscriptenVersion', Exec) {
    dependsOn("emscriptenActivate")
    doFirst {
        println "========================================="
        println "   EMSCRIPTEN COMPILER DIAGNOSTICS"
        println "========================================="
        println "Gradle toolchain path: ${emccCmd}"
        println "========================================="
    }

    if(os.toFamilyName() == "windows") {
        def emccPath = file(emccCmd).absolutePath
        environment("EMSDK_QUIET", 1)
        println(commandLine(
                'cmd',
                '/c',
                "$emsdkEnvCmd && $emccPath",
                "--version"
        ).toString())

    } else {
        println(commandLine(
                emccCmd,
                "--version"
        ).toString())
    }
}

tasks.register('clean', Delete) {
    group = 'build'
    delete "${outputJsPath}"
}

// 5. Register the final cache-compliant automated execution task
tasks.register('compileWasm', Exec) {
    group = 'build'
    description = 'Compiles processor.c into WebAssembly using Emscripten.'

    // Ensure the task automatically triggers if your C source modifications change
    inputs.files fileTree(dir: layout.projectDirectory, include: '*.c')

    outputs.dir(outputDirectory)

    // Ensure the plugin installation executes before this compilation runs
    dependsOn('emscriptenActivate')
    environment("EMSDK_QUIET", 1) // Prevent emsdkEnvCmd from listing all the environment variables

    doFirst {
        // Ensure the output directory exists before compiling
        if (!outputDirectory.exists()) {
            outputDirectory.mkdirs()
        }
    }

    // 2. Define your compiler flags and options
    def emccArgs = [
            "-O3",
            "-flto",
            "-msimd128",
            "-ffast-math",
            "-o", "${outputJsPath}",
            "-s", "WASM=1",
            "-s", "ENVIRONMENT=worklet",
            "-s", "SINGLE_FILE=1",
            "-s", "ALLOW_MEMORY_GROWTH=1",
            "-s", "EXPORTED_RUNTIME_METHODS=['HEAP32','HEAPF32']",
            // MANDATORY: Forces Emscripten to check and execute custom callback hook
            "-s", "INCOMING_MODULE_JS_API=['onRuntimeInitialized']",
            "--post-js", "${rootDir}/client/public/assets/wasm/audio-hooks.js",
            "-s", 'EXPORTED_FUNCTIONS=["_malloc","_free"]',
            "--no-entry"
    ]

    // 3. Combine everything dynamically into the command line
    // Construct the list smoothly without '+' or 'addAll' methods
    def cmd = []
    if(os.toFamilyName() == 'windows') {
        cmd.addAll(["cmd", "/c"])
        cmd.add(emsdkEnvCmd)
        cmd.add("&&")
    }
    cmd.add(emccCmd)
    cmd.addAll(inputs.files.files*.absolutePath as Object[]) // Cast to bypass JetBrains type inspection
    cmd.addAll(emccArgs)

    commandLine = cmd
}

tasks.register('downloadEmscripten', Copy) {
    mkdir("$emscriptenLocation/download")

    def fileName = "$emscriptenVersion" + ".zip"
    File f = new File("$emscriptenLocation/download/$fileName")
    if (!f.exists()) {
        new URI("https://github.com/emscripten-core/emsdk/archive/refs/tags/$fileName").toURL().withInputStream { i -> f.withOutputStream { it << i } }
    }
    def fEmSdkCmd = new File(emsdkCmd)
    if(!fEmSdkCmd.exists()) {
        from(zipTree("$emscriptenLocation/download/$fileName"))
        into("$emscriptenLocation/")
    }
}

tasks.register("emscriptenInstall", UvTask) {
    dependsOn('downloadEmscripten')

    workingDir "$rootDir/.emscripten/emsdk-$emscriptenVersion"
    onlyIf {
        File f = new File(emccCmd)
        !f.exists()
    }

    // Python ios required for installing emscripten
    // 'uv run' will seamlessly download, isolate, and execute using a portable Python 3 runtime
    // without requiring it on your host system.
    args = [
            'run',
            '--no-project',
            '--python', '3.14',
            'emsdk.py', 'install', 'latest'
    ]
 }

tasks.register("emscriptenActivate", Exec) {
    dependsOn("emscriptenInstall")

    onlyIf {
        // Emscripten is only "ready" if the config file exists
        File configFile = new File(project.file(emsdkCmd).parentFile, ".emscripten")
        File f = new File(emccCmd)

        !f.exists() || !configFile.exists()
    }

    // Python not needed here, we can use a normal Exec task
    commandLine(
            emsdkCmd,
            "activate",
            "latest"
    )
}
